version: "3.9"

services:
  auth-service:
    build: ./src/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=Zxyafenvd43790

  backend:
    build: ./src/backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=Zxyafenvd43790
      - AUTH_SERVICE_URL=http://auth-service:5000
    depends_on:
      - auth-service

  frontend:
    build: ./src/jewelry-store
    container_name: jewelry-store
    ports:
      - "3000:80"
    depends_on:
      - backend
