name: CI/CD Pipeline - Luxe Jewelry Store

# 1. Trigger the workflow on pushes to the main branch OR a new tag
on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on any tag starting with 'v' (e.g., v1.0.0)

# Define global environment variables
env:
  DOCKERHUB_REGISTRY: talgold01
  NEXUS_REGISTRY: localhost:8082/docker-hosted  # NOTE: Replace 'localhost:8082/docker-hosted' with your actual external Nexus repository URL (e.g., your-nexus-domain:8082/repository/docker-hosted) if Nexus is not running on the GitHub Actions runner.
  PROJECT_NAME: luxe-jewelry-store-project 
  DEPLOY_ENV: development
  
  # VERSION CONTROL LOGIC
  IMAGE_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.run_id }} 

jobs:
  
  # ====================================================================
  # STABLE CI/CD PIPELINE JOB
  # ====================================================================
  ci_cd_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
      
      # 🔑 Set up Snyk Token once for all scans
      - name: 🔑 Set up Snyk
        uses: snyk/actions/setup@master
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      # --- 🧪 UNIT TESTS STAGE ---

      - name: ⚙️ Set up Python Environment
        uses: actions/setup-python@v5
        with:
          # Pinning to a stable version (like 3.12)
          python-version: '3.12' 

      - name: 📦 Install Pytest Dependency
        run: pip install pytest 

      - name: 🧪 Run Unit Tests
        working-directory: test
        run: pytest --maxfail=1 --disable-warnings -q

      # --- 🏗️ BUILD STAGE (FIXED TAGGING SOURCE) ---

      - name: 🛠️ Setup Docker Compose
        run: docker compose version

      - name: 🏗️ Build and Tag Docker Images for Nexus
        env:
          AUTH_TAG: ${{ env.NEXUS_REGISTRY }}/auth-service:${{ env.IMAGE_VERSION }}
          BACKEND_TAG: ${{ env.NEXUS_REGISTRY }}/backend:${{ env.IMAGE_VERSION }}
          FRONTEND_TAG: ${{ env.NEXUS_REGISTRY }}/frontend:${{ env.IMAGE_VERSION }}
          
          # Adjusted to match the naming from docker-compose build (assuming docker-compose.yml uses '-latest' without colon; best practice is to update docker-compose.yml to use ':latest' for explicit tagging)
          AUTH_SOURCE_TAG: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.PROJECT_NAME }}-auth-service-latest
          BACKEND_SOURCE_TAG: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.PROJECT_NAME }}-backend-latest
          FRONTEND_SOURCE_TAG: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.PROJECT_NAME }}-frontend-latest
          
        run: |
          cd infra
          echo "Starting Docker builds with tag: ${{ env.IMAGE_VERSION }}"
          
          # 1. Build images. These create the source images defined above.
          docker compose build \
            --build-arg IMAGE_VERSION=${{ env.IMAGE_VERSION }} \
            auth-service backend frontend 
          
          # Debug: List all Docker images to verify names
          docker images | grep ${{ env.PROJECT_NAME }} || true
          
          # 2. Manually tag the local images with the correct Nexus tag.
          docker tag $AUTH_SOURCE_TAG $AUTH_TAG
          docker tag $BACKEND_SOURCE_TAG $BACKEND_TAG
          docker tag $FRONTEND_SOURCE_TAG $FRONTEND_TAG
          
          # Best practice: If on main branch, also tag and prepare :latest for push
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag $AUTH_SOURCE_TAG ${{ env.NEXUS_REGISTRY }}/auth-service:latest
            docker tag $BACKEND_SOURCE_TAG ${{ env.NEXUS_REGISTRY }}/backend:latest
            docker tag $FRONTEND_SOURCE_TAG ${{ env.NEXUS_REGISTRY }}/frontend:latest
          fi
          
          echo "All images successfully built and tagged for Nexus."

      # --- 🐳 SECURITY SCAN STAGE (Post-Build/Image-Based) ---

      - name: 🛡️ Snyk Final Image Scan (auth-service)
        uses: snyk/actions/docker@master
        env:
          AUTH_TAG: ${{ env.NEXUS_REGISTRY }}/auth-service:${{ env.IMAGE_VERSION }}
        with:
          image: ${{ env.AUTH_TAG }}
          severity: critical

      - name: 🛡️ Snyk Final Image Scan (backend)
        uses: snyk/actions/docker@master
        env:
          BACKEND_TAG: ${{ env.NEXUS_REGISTRY }}/backend:${{ env.IMAGE_VERSION }}
        with:
          image: ${{ env.BACKEND_TAG }}
          severity: critical

      - name: 🛡️ Snyk Final Image Scan (frontend)
        uses: snyk/actions/docker@master
        env:
          FRONTEND_TAG: ${{ env.NEXUS_REGISTRY }}/frontend:${{ env.IMAGE_VERSION }}
        with:
          image: ${{ env.FRONTEND_TAG }}
          severity: critical

      # --- 🚀 PUSH STAGE ---

      - name: 🔑 Log in to Nexus Repository (via Docker CLI)
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ env.NEXUS_REGISTRY }} \
          --username ${{ secrets.NEXUS_USERNAME }} \
          --password-stdin
      
      - name: 🚀 Push Images to Nexus (Version Control Implemented)
        env:
          AUTH_TAG: ${{ env.NEXUS_REGISTRY }}/auth-service:${{ env.IMAGE_VERSION }}
          BACKEND_TAG: ${{ env.NEXUS_REGISTRY }}/backend:${{ env.IMAGE_VERSION }}
          FRONTEND_TAG: ${{ env.NEXUS_REGISTRY }}/frontend:${{ env.IMAGE_VERSION }}
        run: |
          docker push $AUTH_TAG
          docker push $BACKEND_TAG
          docker push $FRONTEND_TAG
          
          # Best practice: If on main branch, also push :latest tags
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker push ${{ env.NEXUS_REGISTRY }}/auth-service:latest
            docker push ${{ env.NEXUS_REGISTRY }}/backend:latest
            docker push ${{ env.NEXUS_REGISTRY }}/frontend:latest
          fi

      # --- ☁️ DEPLOYMENT & CLEANUP ---
      
      - name: ☁️ Deploy Services (Placeholder for Remote Deploy)
        run: |
          echo "Deployment to ${{ env.DEPLOY_ENV }} initiated using images tagged with version: ${{ env.IMAGE_VERSION }}"

      - name: 🧹 Cleanup Docker Resources
        if: always()
        run: docker system prune -af